# ¡Bienvenidos a la segunda semana del Mastery Data Science: Pandas!

### Objetivo de la sesión 2 semana 2: 

* Conocer las ventajas de utilizar Pandas.
* Cargar un conjunto de datos utilizando Pandas.
* Conocer y utlilizar las operaciones básicas de Pandas.
* Localizar posibles aplicaciones

#Antes de empezar, un repaso
En la última sesión vimos como usar arreglos de Numpy.

*   ¿cómo importar la librería de numpy?
*   ¿cómo se creaba un arreglo de una dimensión en Numpy?

## 1. Introducción

### 1.1 Numpy vs Pandas

*Pandas* es un librería de Python para el análisis de datos, la cual esta construida sobre múltiples librerías, entre ellas esta Numpy. Ofrece múltiples herramientas para la exploración, limpieza y trasformación de datos, las cuales son procesos críticos al trabajar con datos en Python.

### 1.2 Recursos externos

Al ser una herramienta tan completa, es imposible cubrir todas sus operaciones en la sesión, por ello recomendamos las siguientes fuentes 

- Documentación oficial: http://pandas.pydata.org/pandas-docs/stable/
- *Python for Data Analysis* por *Wes McKinney*
- *Python Data Science Handbook* por Jake VanderPlas

### 1.3 Antes de empezar

#### 1.3.1 ¿Cómo importar *pandas*? 

Podemos hacerlo de la manera tradicional y es comunmnete renombrada como *pd*

In [0]:
import pandas as pd

#Carguemos tambien Numpy para realizar ciertas operaciones
import numpy as np

#### 1.3.2 Estructuras: Series, Dataframe, Panel 

Aquí encontraremos las estructuras básicas que se útilizan en Pandas



#### Series

Es un arreglo unidimensional capaz que puede conter cualquier tipo de datos y poseen una etiqueta para identificación

In [0]:
# Creemos nuestra primera Serie desde un arreglo de Numpy
s = pd.Series(np.random.randn(5))
s

0   -0.557816
1   -0.753768
2   -0.289375
3    1.135719
4    1.010407
dtype: float64

In [0]:
# Podemos indicar la etiqueda(índice) de nuestros datos 
s = pd.Series(np.random.randn(5),index=['a','b','c','d','e'])
s

a    0.468816
b    0.872587
c   -0.641121
d    0.684919
e   -0.460794
dtype: float64

In [0]:
 # Y tambien podemos crearla desde un diccionario 
  d = {'b': 1, 'a': 0, 'c': 2}
  s2=pd.Series(d)
  
  # ¡Toma las llaves como los índices!
  s2

b    1
a    0
c    2
dtype: int64

In [0]:
# Operan muy similiarmente a los arreglos de Numpy

#Funcionan como una arreglo 
print(s2[2]*10)
print()

# Pero tambien funcionan como diccionario
print(s2['c']*10)
print()

# En este caso nos devuelve también el índice
print(s2[:2]*10) 
print()

# Y podemos usarlas como vectores para operaciones 
print(np.exp(s2))

#### Dataframes 

Es un arreglo de columnas, puede ser visto como un conjunto series: ahora tenemos índices y columnas

In [0]:
# Creacion desde un diccionario de series 
d = {'Uno': pd.Series([1., 2., 3.], index=['a', 'b', 'c']), 'Dos': pd.Series([1., 2., 3., 4.], index=['a', 'b', 'c', 'd'])}

pd.DataFrame(d)

   Uno  Dos
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [0]:
# Creado entradas de indices y columnas, las cuales se llena como NaN (Not A Number)
pd.DataFrame(d,index=['a','b','f'], columns=['Dos','Tres'])

   Dos Tres
a  1.0  NaN
b  2.0  NaN
f  NaN  NaN

## 2. Uso básico de Pandas

A continucación realizaremos algunas operaciones básicas y útiles para usar en nuestra siguiente sección

In [0]:
# Consideremos la creación de un dataframe desde un diccionario

D={'A':pd.Series([100,200,300,400], index=['a','b','c','d']),'B':pd.Series([111,222,444],index=['a','b','d'])}

df=pd.DataFrame(D)
df

     A      B
a  100  111.0
b  200  222.0
c  300    NaN
d  400  444.0

In [0]:
# Obtengamos los índices del dataframe
df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [0]:
# Obtengamos las columnas 
df.columns

Index(['A', 'B'], dtype='object')

In [0]:
# Seleccionemos una columna 
df['A']

a    100
b    200
c    300
d    400
Name: A, dtype: int64

In [0]:
# Creando columnas mediante la operación de columnas 
df['C']=df['A']%200==0 
df['D']=df['A']*df['B']
df['E']=df['A']*df['C']
df

     A      B         D    E      C
a  100  111.0   11100.0    0  False
b  200  222.0   44400.0  200   True
c  300    NaN       NaN    0  False
d  400  444.0  177600.0  400   True

In [0]:
# Borrando columnas de manera rápida 
del df['C']
df

     A      B         D    E
a  100  111.0   11100.0    0
b  200  222.0   44400.0  200
c  300    NaN       NaN    0
d  400  444.0  177600.0  400

In [0]:
# Podemos traer la una fila mediante su posición 

pd.DataFrame(df.iloc[0])

         a
A    100.0
B    111.0
D  11100.0
E      0.0

In [0]:
# O mediante su índice 
pd.DataFrame(df.loc['a'])

         a
A    100.0
B    111.0
D  11100.0
E      0.0

## 3. Ejercicios 


**Ejercicio 1: ** Películas

In [0]:

from google.colab import drive
drive.mount('/content/drive/')

with open('content/drive/My Drive/Colab Notebooks/movielens/links.csv') as f:
  f.read()

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

FileNotFoundError: ignored

In [0]:
 terpath="content/drive/My Drive/Colab Notebooks/movielens/links.csv"

#path="My Drive/Colab Notebooks/movielens/links.csv"
movies=pd.read_csv(path)

FileNotFoundError: ignored

# Matplotlib

Ahora que ya sabemos como cargar un conjunto de datos, vamos a visualizarlos. Con gráficos de líneas, diagramas de dispersión, histogramas, etc.